language: node_js
node_js:
 - "8.11"

branches:
  only:
    - master

addons:
  chrome: stable

before_script:
  - yarn global add @angular/cli

cache:
  yarn: true
  directories:
    - node_modules

script:
  - npm i -g npm@6.1.0
  - p=$(which npm)
  - rm $p
  - ln -s /home/travis/.nvm/versions/node/v10.1.0/bin/npm $p || true
  - npm -v
  - ng build --prod


deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: ./dist/
  on:
